### ISSUE TITLE
[Bug-Candidate]:  Err value in src/core/core_unit.rs

### ISSUE THREAD

**Issue by ThomasHeim11** [crytic/caracal#60]
### Describe the issue:

When I run  'caracal detect apps/blockchain/starknet' for my project  i get an error in  'src/core/core_unit.rs file, line 31 where Result::unwrap() is called.

### Code example to reproduce the issue:

Scarb.toml
```javascript
[package]
name = "starklane"
version = "0.1.0"

[dependencies]
starknet = "2.6.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.11.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.19.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[cairo]
sierra-replace-ids = true

[lib]

[tool.sncast.katana]
account = "katana_account"
url = "http://127.0.0.1:5050"
```

### Version:

caracal 0.2.3

### Relevant log output:

```shell
Compiling with Scarb. Found Scarb.toml.
thread '<unnamed>' panicked at src/core/core_unit.rs:31:78:
called `Result::unwrap()` on an `Err` value: TypeSpecialization { concrete_id: ConcreteTypeId { id: 4, debug_name: Some("Const<u128, 18446744073709551616>") }, error: TypeSpecialization { type_id: GenericTypeId("Const"), error: UnsupportedId("Const") } }
stack backtrace:
thread 'thread '<unnamed>' panicked at src/core/core_unit.rs:31:<unnamed>' panicked at src/core/core_unit.rs78:
called `Result::unwrap()` on an `Err` value: TypeSpecialization { concrete_id: ConcreteTypeId { id: 2, debug_name: Some("Const<felt252, 5420154128225384396790819266608>") }, error: TypeSpecialization { type_id: GenericTypeId("Const"), error: UnsupportedId("Const") } }
:31:78:
called `Result::unwrap()` on an `Err` value: TypeSpecialization { concrete_id: ConcreteTypeId { id: 1, debug_name: Some("Const<u32, 30>") }, error: TypeSpecialization { type_id: GenericTypeId("Const"), error: UnsupportedId("Const") } }
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   3: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   4: rayon::iter::plumbing::Folder::consume_iter
   5: rayon::iter::plumbing::bridge_producer_consumer::helper
   6: rayon_core::join::join_context::{{closure}}
   7: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   8: rayon_core::registry::WorkerThread::wait_until_cold
   9: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   3: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   4: rayon::iter::plumbing::Folder::consume_iter
   5: rayon::iter::plumbing::bridge_producer_consumer::helper
   6: rayon_core::join::join_context::{{closure}}
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   9: rayon_core::registry::WorkerThread::wait_until_cold
  10: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   3: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   4: rayon::iter::plumbing::Folder::consume_iter
   5: rayon::iter::plumbing::bridge_producer_consumer::helper
   6: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   7: rayon_core::registry::WorkerThread::wait_until_cold
   8: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by elec7rik** [comment]
Hi Thomas,
I am unable recognize this program. Would you kindly explain more on why I
got this email and if I am the intended recipient?

Thank you, Vicky.
